### ISSUE TITLE
 'markdown_it.utils' has no attribute 'OptionsType'

### ISSUE THREAD

**Issue by j77h** [actionless/pikaur#755]
```
pikaur -Vq

Pikaur v1.17
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

#### Description:

Today I upgraded Manjaro Stable
(last release announcement was on 2023-08-11)
and as usual ran `pikaur -Qua --devel` after rebooting.

This got `aur/pikaur   1.17-1 -> 1.18.3-1`, among others,
and as usual I tried to re-install pikaur before the others,
but `pikaur -S pikaur` got an error,
and then `makepkg -fsri` got the same error.

In case it's significant, one of the others is
`aur/pymdown-extensions   10.1-1 -> 10.2-2`

#### Logs:

```
pikaur -S pikaur
...
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
| xargs --null xgettext --language=python --add-comments --sort-output \
--default-domain=pikaur --from-code=UTF-8 \
--keyword='translate' --keyword='translate_many:1,2' \
--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
................................ done.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
............................... done.
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
Traceback (most recent call last):
File "/home/jh/.cache/pikaur/build/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
OptionsType = markdown_it.utils.OptionsType
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
..........................make: *** [Makefile:48: pikaur.1] Error 1
make: *** Waiting for unfinished jobs....
... done.
==> ERROR: A failure occurred in build().
Aborting...
```

Note: `bsdtar: Failed to set default locale` is normal for me for the past ~8 years.
(It's a result of mixing YMD date format with English.)
```
makepkg -fsri
==> Making package: pikaur 1.18.3-1 (Tue Aug 29 19:18:56 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Downloading pikaur-1.18.3.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2159k    0 2159k    0     0   228k      0 --:--:--  0:00:09 --:--:--  252k
==> Validating source files with b2sums...
pikaur-1.18.3.tar.gz ... Passed
==> Extracting sources...
-> Extracting pikaur-1.18.3.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Starting build()...
# find pikaur -type f -name '*.py' -not -name 'argparse.py' \
#
/usr/bin/python ./maintenance_scripts/pikaman.py README.md pikaur.1
find pikaur -type f -name '*.py' -print0 \
| xargs --null xgettext --language=python --add-comments --sort-output \
--default-domain=pikaur --from-code=UTF-8 \
--keyword='translate' --keyword='translate_many:1,2' \
--output=locale/pikaur.pot
xgettext: The option '--sort-output' is deprecated.
mkdir -p dist/usr/bin
test -f locale/fr.po || msginit --locale=fr --no-translator --input=locale/pikaur.pot --output=locale/fr.po
msgmerge --update locale/fr.po locale/pikaur.pot
................................ done.
test -f locale/ru.po || msginit --locale=ru --no-translator --input=locale/pikaur.pot --output=locale/ru.po
msgmerge --update locale/ru.po locale/pikaur.pot
................................ done.
test -f locale/pt.po || msginit --locale=pt --no-translator --input=locale/pikaur.pot --output=locale/pt.po
msgmerge --update locale/pt.po locale/pikaur.pot
.............................. done.
test -f locale/pt_BR.po || msginit --locale=pt_BR --no-translator --input=locale/pikaur.pot --output=locale/pt_BR.po
msgmerge --update locale/pt_BR.po locale/pikaur.pot
................................ done.
test -f locale/de.po || msginit --locale=de --no-translator --input=locale/pikaur.pot --output=locale/de.po
msgmerge --update locale/de.po locale/pikaur.pot
Traceback (most recent call last):
File "/home/jh/pikaur/src/pikaur-1.18.3/./maintenance_scripts/pikaman.py", line 31, in <module>
OptionsType = markdown_it.utils.OptionsType
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'markdown_it.utils' has no attribute 'OptionsType'. Did you mean: 'OptionsDict'?
................................. done.
make: *** [Makefile:48: pikaur.1] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
Aborting...
```

**Comment by j77h** [comment]
My apologies. Forgot to engage brain before opening mouth.

After upgrading '`markdown-it-py`' from 2.2.0 to 3.0.0, '`pikaur`' works fine.

My `markdown-it-py` was installed via `pip`, and I usually do the pip upgrades last.

**Comment by actionless** [comment]
you could also simply skip pikaur's upgrade til markdown thing got updated in manjaro

or skip building documentation while editing pikaur's PKGBUILD:

replace `make` to `make locale bin`

(markdown needed only during the build of the manpage)
